default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: "qaZcAqnZfYdN7RHwiM3HvMZMjxUxNN&(hy7omCp^ZBVCnH8vDo"
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
